eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-register: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
okta:
  oauth2:
    issuer: https://dev-53330324.okta.com/oauth2/default
    audience: api://default      
